import { EmployeeDashboardIndex } from './pages/Employees/EmployeeDashboardIndex';

// ...existing code...

function App() {
    // ...existing code...
    return (
        // ...existing code...
        <Routes>
            // ...existing routes...
            <Route path="/auth/employee/employee-dashboard-index" element={<EmployeeDashboardIndex />} />
            // ...existing routes...
        </Routes>
        // ...existing code...
    );
}

// ...existing code...